stages:
  - docker-build
  - deploy

variables:
  KUBECONFIG: /etc/deploy/config
docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" focus-spa/
    - docker push "$CI_REGISTRY_IMAGE:latest"
  except:
    - master
deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.5.3
  before_script:
    - mkdir -p /etc/deploy
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - kubectl config use-context do-sfo3-focuscluster-cluster
  script:
    - helm install -f helm/spa/test-spa/values.yaml focusspa helm/spa/test-spa/